name: Build & Push to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Dockerhub
      run: echo dckr_pat_dFHRGrzew4vFNMctMrCMkgXbP2M | docker login -u finpace --password-stdin

    - name: Build intermediate Docker image
      run: docker build -f deployment/docker/Dockerfile -t finpace/pdf-libs:tmp .

    - name: Build the Docker image
      run: docker build -f deployment/docker/Dockerfile-no-tests -t finpace/pdf-libs .

    - name: Push the Docker image
      run: docker push finpace/pdf-libs:latest